import { BellRing, CheckCircle2, ChevronLeft, LayoutDashboard, ListChecks, Menu, NotebookTabs, PanelTop, Scale, UserRound, UsersRound } from "lucide-react";
import React, { useState, type ReactNode } from "react";

type OptionId = "reference" | "ledger" | "focus";

const optionMeta: Record<OptionId, { number: string; title: string; subtitle: string; icon: typeof LayoutDashboard; accent: string }> = {
  reference: { number: "1", title: "المطابق لتكوين الصورة", subtitle: "الأقرب إلى المرجع: شريط رفيع، خمسة مؤشرات، مهام واسعة، وتنبيهات وفريق في العمود المقابل.", icon: LayoutDashboard, accent: "bg-[#0b5c45]" },
  ledger: { number: "2", title: "دفتر المتابعة القضائي", subtitle: "نسخة أكثر رسمية وكثافة: سطور تشبه سجل العمل، فواصل وثائقية، وإشارات حالة منضبطة.", icon: NotebookTabs, accent: "bg-[#18352c]" },
  focus: { number: "3", title: "التركيز اليومي المتجاوب", subtitle: "نسخة أبسط وأوضح للجوال: الأولوية للمهام الحالية، ثم التنبيهات والفريق دون ازدحام.", icon: PanelTop, accent: "bg-[#2f7656]" },
};

function MiniStatus({ label, value, tone }: { label: string; value: string; tone: string }) {
  return <div className={`rounded-md border px-2 py-1.5 ${tone}`}><div className="flex items-center justify-between"><span className="text-[7px] font-black">{label}</span><span className="text-sm font-black">{value}</span></div><div className="mt-1 h-px bg-current opacity-15" /></div>;
}

function MiniTask({ title, state = "قيد المعالجة" }: { title: string; state?: string }) {
  return <div className="flex items-center gap-2 border-b border-[#e8e5dd] py-2 last:border-0"><span className="grid h-5 w-5 place-items-center rounded bg-[#f3ece8] text-[#a8493b]"><ListChecks className="h-3 w-3" /></span><span className="min-w-0 flex-1"><span className="block truncate text-[8px] font-black text-[#29463b]">{title}</span><span className="block text-[6px] text-[#849088]">قسم التسليم · الاستحقاق 11:00 ص</span></span><span className="rounded-full bg-[#eef6f0] px-1.5 py-0.5 text-[6px] font-bold text-[#2f7656]">{state}</span></div>;
}

function ReferenceOption() {
  return <div className="rounded-xl border border-[#dedbd1] bg-[#f8f7f1] p-3 shadow-sm" dir="rtl"><div className="flex items-center justify-between border-b border-[#e2dfd6] pb-2"><div className="flex items-center gap-1.5"><Menu className="h-3.5 w-3.5 text-[#25463a]" /><span className="grid h-5 w-5 place-items-center rounded bg-[#e4efe6]"><Scale className="h-3 w-3 text-[#0b5c45]" /></span><span className="text-[8px] font-black text-[#18352c]">رَكيزة · المحكمة العمالية</span></div><div className="flex items-center gap-1"><BellRing className="h-3 w-3 text-[#b68a35]" /><span className="grid h-5 w-5 place-items-center rounded-full bg-[#e6f0e7]"><UserRound className="h-3 w-3 text-[#2f7656]" /></span></div></div><div className="mt-3 flex items-end justify-between"><div><p className="text-[7px] font-bold text-[#b68a35]">لوحة متابعة عملية</p><p className="text-sm font-black text-[#18352c]">مرحباً بك، عبدالعزيز</p><p className="mt-0.5 text-[6px] text-[#819087]">نظرة مركزة على أعمال المحكمة وأداء الأقسام</p></div><p className="text-left text-[6px] font-semibold text-[#75827b]">الثلاثاء، 4 أغسطس<br />13 ربيع الأول 1448هـ</p></div><div className="mt-3 grid grid-cols-5 gap-1"><MiniStatus label="مهام اليوم" value="9" tone="border-[#c8dfcc] bg-[#edf7ee] text-[#216345]" /><MiniStatus label="قرب موعدها" value="0" tone="border-[#eadba7] bg-[#fff9e8] text-[#8b6b25]" /><MiniStatus label="بدأ التنفيذ" value="0" tone="border-[#c9d8e7] bg-[#eef5fb] text-[#356285]" /><MiniStatus label="بانتظار اعتمادي" value="3" tone="border-[#dfd0eb] bg-[#f6f0fb] text-[#70458c]" /><MiniStatus label="متأخرة" value="0" tone="border-[#ebc8c0] bg-[#fff0ed] text-[#a8493b]" /></div><div className="mt-3 grid gap-2 grid-cols-[minmax(0,1fr)_6.2rem]"><div className="rounded-lg bg-white p-2"><div className="flex items-center justify-between"><span className="text-[8px] font-black text-[#18352c]">مهامي اليوم</span><span className="text-[6px] text-[#2f7656]">عرض الكل</span></div><MiniTask title="تزويد الملازمين بوسيلة التواصل" /><MiniTask title="تسجيل طلبات الموارد والمرفقات" /><MiniTask title="متابعة طلبات الإجازات" /></div><div className="space-y-2"><div className="rounded-lg bg-white p-2"><span className="text-[8px] font-black text-[#18352c]">التنبيهات</span><p className="mt-2 text-[6px] text-[#7a8880]">لا توجد تنبيهات تحتاج إجراءً حالياً</p></div><div className="rounded-lg bg-white p-2"><span className="text-[8px] font-black text-[#18352c]">الفريق</span><div className="mt-2 space-y-1 text-[6px] text-[#527064]"><p>● أحمد العتيبي</p><p>● إبراهيم السعيد</p><p>● عبدالله القحطاني</p></div></div></div></div></div>;
}

function LedgerOption() {
  return <div className="rounded-xl border border-[#d9d4c9] bg-[#fbfaf5] p-3 shadow-sm" dir="rtl"><div className="flex items-center justify-between border-y-2 border-[#18352c] py-2"><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-sm bg-[#18352c] text-white"><Scale className="h-3.5 w-3.5" /></span><div><p className="text-[8px] font-black text-[#18352c]">سجل المتابعة اليومي</p><p className="text-[6px] text-[#7c7a71]">المحكمة العمالية بالرياض</p></div></div><span className="rounded-sm border border-[#b68a35] px-2 py-1 text-[6px] font-black text-[#8b6b25]">04 / 08 / 2026</span></div><div className="mt-3 grid grid-cols-[1fr_6rem] gap-2"><div className="border border-[#ded9cf] bg-white"><div className="grid grid-cols-[1.5rem_1fr_3.5rem_3.6rem] border-b border-[#ded9cf] bg-[#f1eee5] px-2 py-1 text-[6px] font-black text-[#516057]"><span>م</span><span>بيان العمل</span><span>الوقت</span><span>الحالة</span></div>{["تزويد الملازمين بالتواصل", "طلبات الموارد والمرفقات", "متابعة الإجازات", "تحديث قاعدة البيانات"].map((item, index) => <div key={item} className="grid grid-cols-[1.5rem_1fr_3.5rem_3.6rem] items-center border-b border-[#eeeae1] px-2 py-1.5 last:border-0"><span className="text-[7px] text-[#8b6b25]">0{index + 1}</span><span className="truncate text-[7px] font-bold text-[#29463b]">{item}</span><span className="text-[6px] text-[#75827b]">11:00 ص</span><span className="text-[6px] font-bold text-[#2f7656]">قيد المعالجة</span></div>)}</div><div className="space-y-2"><div className="border border-[#ded9cf] bg-white p-2"><p className="text-[7px] font-black text-[#18352c]">ملخص السجل</p><p className="mt-2 text-lg font-black text-[#0b5c45]">9</p><p className="text-[6px] text-[#75827b]">إجمالي مهام اليوم</p></div><div className="border border-[#ded9cf] bg-white p-2"><p className="text-[7px] font-black text-[#18352c]">ملاحظات</p><p className="mt-2 text-[6px] leading-4 text-[#75827b]">لا توجد ملاحظات عاجلة مسجلة لهذا اليوم.</p></div></div></div><div className="mt-3 flex items-center justify-between border-t border-[#ded9cf] pt-2"><span className="text-[6px] text-[#75827b]">سجل تشغيلي داخلي · للاستخدام الإداري</span><span className="text-[6px] font-black text-[#18352c]">رَكيزة</span></div></div>;
}

function FocusOption() {
  return <div className="rounded-xl border border-[#d8e3da] bg-[#f6faf6] p-3 shadow-sm" dir="rtl"><div className="flex items-center justify-between"><div className="flex items-center gap-1.5"><span className="grid h-6 w-6 place-items-center rounded-lg bg-[#0b5c45] text-white"><Scale className="h-3.5 w-3.5" /></span><p className="text-[8px] font-black text-[#18352c]">رَكيزة</p></div><div className="flex items-center gap-2"><BellRing className="h-3.5 w-3.5 text-[#b68a35]" /><Menu className="h-3.5 w-3.5 text-[#18352c]" /></div></div><div className="mt-4 rounded-lg bg-[#0b5c45] px-3 py-3 text-white"><p className="text-[7px] text-[#d7e7d9]">الثلاثاء، 4 أغسطس</p><p className="mt-1 text-base font-black">مرحباً بك، عبدالعزيز</p><p className="mt-1 text-[6px] text-[#d7e7d9]">لديك 3 مهام تحتاج مراجعة اليوم.</p></div><div className="mt-3 grid grid-cols-3 gap-1.5"><div className="rounded-lg bg-white p-2"><p className="text-[6px] text-[#75827b]">اليوم</p><p className="mt-1 text-lg font-black text-[#0b5c45]">9</p></div><div className="rounded-lg bg-white p-2"><p className="text-[6px] text-[#75827b]">قيد التنفيذ</p><p className="mt-1 text-lg font-black text-[#356285]">0</p></div><div className="rounded-lg bg-white p-2"><p className="text-[6px] text-[#75827b]">المتأخرة</p><p className="mt-1 text-lg font-black text-[#a8493b]">0</p></div></div><div className="mt-3 rounded-lg bg-white p-2.5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black text-[#18352c]">أولوية اليوم</p><p className="text-[6px] text-[#75827b]">المهام الأقرب للاستحقاق</p></div><CheckCircle2 className="h-4 w-4 text-[#2f7656]" /></div><MiniTask title="تزويد الملازمين بوسيلة التواصل" state="ابدأ الآن" /><MiniTask title="تسجيل طلبات الموارد والمرفقات" state="عرض التفاصيل" /><button type="button" className="mt-2 w-full rounded-md bg-[#e5f0e7] py-1.5 text-[7px] font-black text-[#2f7656]">فتح جميع المهام</button></div><div className="mt-3 flex items-center justify-between rounded-lg border border-[#d8e3da] bg-white p-2"><div className="flex items-center gap-2"><UsersRound className="h-3.5 w-3.5 text-[#2f7656]" /><span className="text-[7px] font-bold text-[#29463b]">الفريق والتواصل</span></div><ChevronLeft className="h-3.5 w-3.5 text-[#2f7656]" /></div></div>;
}

export default function DashboardOptionsPage() {
  const [selected, setSelected] = useState<OptionId | null>(null);
  const cards: Array<{ id: OptionId; preview: ReactNode }> = [
    { id: "reference", preview: <ReferenceOption /> },
    { id: "ledger", preview: <LedgerOption /> },
    { id: "focus", preview: <FocusOption /> },
  ];

  return <main className="min-h-screen bg-[#f7f5ee] px-4 py-8 text-right" dir="rtl"><section className="mx-auto max-w-[1450px]"><div className="border-b border-[#ddd9cf] pb-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[#0b5c45]"><Scale className="h-5 w-5" /><span className="text-xs font-black">رَكيزة · معاينة تصميم اللوحة</span></div><h1 className="mt-2 text-3xl font-black text-[#18352c]">اختر التكوين الأقرب إلى الصورة المرجعية</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-[#66786e]">هذه نماذج عرض فقط؛ لم يتم تغيير لوحة التشغيل بها. اختر رقماً واحداً، ثم أبني اللوحة الفعلية عليه بكل بياناتها وصلاحياتها.</p></div><span className="rounded-full border border-[#d9d3c5] bg-white px-4 py-2 text-xs font-bold text-[#8b6b25]">ثلاثة نماذج للمقارنة</span></div></div><div className="mt-7 grid gap-6 xl:grid-cols-3">{cards.map(({ id, preview }) => { const meta = optionMeta[id]; const Icon = meta.icon; const active = selected === id; return <article key={id} className={`overflow-hidden rounded-[1.6rem] border bg-white shadow-[0_12px_32px_rgba(30,51,42,0.06)] ${active ? "border-[#0b5c45] ring-2 ring-[#0b5c45]/15" : "border-[#e3dfd5]"}`}><div className={`${meta.accent} px-5 py-4 text-white`}><div className="flex items-center justify-between"><span className="grid h-8 w-8 place-items-center rounded-full bg-white/15 text-sm font-black">{meta.number}</span><Icon className="h-5 w-5" /></div><h2 className="mt-3 text-lg font-black">{meta.title}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-white/80">{meta.subtitle}</p></div><div className="bg-[#f3f1ea] p-4">{preview}</div><div className="p-4"><button type="button" onClick={() => setSelected(id)} className={`w-full rounded-xl px-4 py-3 text-sm font-black ${active ? "bg-[#0b5c45] text-white" : "bg-[#eaf2ea] text-[#0b5c45] hover:bg-[#dcebdd]"}`}>{active ? "تم تحديد هذا النموذج" : `اختيار النموذج ${meta.number}`}</button></div></article>; })}</div>{selected ? <div className="mt-7 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#c8dfcc] bg-[#eef7ef] px-5 py-4"><div><p className="text-sm font-black text-[#0b5c45]">تم تحديد: النموذج {optionMeta[selected].number} — {optionMeta[selected].title}</p><p className="mt-1 text-xs text-[#5d7468]">أرسل لي «اعتمد النموذج {optionMeta[selected].number}» وسأعيد بناء لوحة التشغيل عليه.</p></div><span className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-[#0b5c45]">الاختيار لا يغير المنصة الآن</span></div> : <p className="mt-7 text-center text-sm font-bold text-[#65766d]">اختر نموذجاً من النماذج الثلاثة، ثم أرسل رقمه لاعتماده.</p>}</section></main>;
}
