import React, { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

export function DecisionsPage() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const items = trpc.court.decisions.list.useQuery();
  const [form, setForm] = useState({ kind: "circular" as "decision" | "circular", title: "", body: "" });
  const create = trpc.court.decisions.create.useMutation({ onSuccess: () => { setForm({ kind: "circular", title: "", body: "" }); void utils.court.decisions.list.invalidate(); } });
  const publish = trpc.court.decisions.publish.useMutation({ onSuccess: () => void utils.court.decisions.list.invalidate() });
  const read = trpc.court.decisions.markRead.useMutation();
  const canPublish = user?.role === "admin";
  return <DashboardLayout><section className="mx-auto max-w-6xl"><header><p className="text-xs font-bold tracking-[0.14em] text-[#b18448]">حوكمة المحكمة</p><h1 className="mt-2 text-3xl font-bold text-[#12352f]">القرارات والتعاميم</h1><p className="mt-2 text-sm leading-7 text-[#65766d]">منشورات رسمية قابلة للتتبع، مع قصر تعاميم الوحدات على نطاقها وتسجيل إثبات القراءة.</p></header><div className={`mt-7 grid gap-5 ${canPublish ? "xl:grid-cols-[22rem_minmax(0,1fr)]" : ""}`}>{canPublish && <form onSubmit={event => { event.preventDefault(); create.mutate(form); }} className="rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5 shadow-sm"><h2 className="font-bold text-[#12352f]">إنشاء منشور</h2><select value={form.kind} onChange={event => setForm({ ...form, kind: event.target.value as typeof form.kind })} className="mt-4 h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="circular">تعميم</option><option value="decision">قرار</option></select><Input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="العنوان" className="mt-3" /><textarea required value={form.body} onChange={event => setForm({ ...form, body: event.target.value })} placeholder="نص القرار أو التعميم" className="mt-3 min-h-32 w-full rounded-md border border-input p-3 text-sm" /><Button disabled={create.isPending} className="mt-4 w-full bg-[#12352f]">حفظ كمسودة</Button>{create.error && <p className="mt-3 text-xs text-[#a04a35]">{create.error.message}</p>}</form>}<section className="rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5 shadow-sm"><h2 className="font-bold text-[#12352f]">المنشورات المتاحة</h2>{items.isLoading ? <p className="mt-5 text-sm text-[#738179]">جارٍ تحميل المنشورات…</p> : items.data?.length ? <div className="mt-4 divide-y divide-[#eee8de]">{items.data.map(item => <article key={item.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full bg-[#edf3eb] px-2.5 py-1 text-xs font-bold text-[#386048]">{item.kind === "decision" ? "قرار" : "تعميم"}</span><h3 className="mt-2 font-bold text-[#29463b]">{item.title}</h3></div><div className="flex gap-2">{canPublish && item.status === "draft" && <Button size="sm" onClick={() => publish.mutate({ id: item.id })}>نشر</Button>}<Button size="sm" variant="outline" onClick={() => read.mutate({ decisionId: item.id })}>تسجيل القراءة</Button></div></div><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-[#566a60]">{item.body}</p><p className="mt-2 text-xs text-[#87938c]">{item.publishedAt ? new Date(item.publishedAt).toLocaleString("ar-SA") : "مسودة غير منشورة"}</p></article>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-[#d8d1c5] p-8 text-center text-sm text-[#738179]">لا توجد منشورات متاحة ضمن نطاقك.</p>}</section></div></section></DashboardLayout>;
}
