import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArchiveRestore, CircleDashed, FileCheck2, ShieldAlert } from "lucide-react";
import React, { useState } from "react";
import { toast } from "sonner";

const entityLabels: Record<string, string> = { task: "مهمة", delay: "متعثر", decision: "قرار", disciplinary_action: "مساءلة", score_adjustment: "تعديل نقاط" };
const statusLabels: Record<string, string> = { returned: "أعيد للمراجعة", approved: "معتمد", rejected: "مرفوض", cancelled: "ملغى" };
type ArchiveEntityType = "" | "task" | "delay" | "decision" | "disciplinary_action" | "score_adjustment";
type ArchiveStatus = "" | "returned" | "approved" | "rejected" | "cancelled";

export function GovernanceArchivePage() {
  const [entityType, setEntityType] = useState<ArchiveEntityType>("");
  const [status, setStatus] = useState<ArchiveStatus>("");
  const [query, setQuery] = useState("");
  const archive = trpc.court.archive.governance.useQuery({ entityType: entityType || undefined, status: status || undefined });
  const operationalArchive = trpc.court.tasks.archived.useQuery({ limit: 300 });
  const restore = trpc.court.tasks.restoreArchived.useMutation({ onSuccess: () => operationalArchive.refetch() });
  const archiveOperational = trpc.court.tasks.archiveOperational.useMutation({ onSuccess: () => operationalArchive.refetch() });
  const unitsApi = (trpc.court as any).units;
  const units = unitsApi?.archived?.useQuery ? unitsApi.archived.useQuery() : { data: [] as Array<{ id: number; name: string; isActive?: boolean }>, isLoading: false, error: null, refetch: async () => undefined };
  const setUnitActive = unitsApi?.setActive?.useMutation ? unitsApi.setActive.useMutation({ onSuccess: () => { units.refetch(); toast.success("تم أرشفة أو تفعيل القسم دون حذف بياناته."); } }) : { mutate: () => undefined, isPending: false };
  const matchesQuery = (value: string) => !query.trim() || value.toLowerCase().includes(query.trim().toLowerCase());
  const filteredArchive = (archive.data ?? []).filter(row => matchesQuery(`${row.approval.entityType} ${row.approval.entityId} ${row.approval.requestNote || ""} ${row.approval.decisionNote || ""} ${row.requesterName || ""} ${row.deciderName || ""}`));
  const filteredTasks = (operationalArchive.data?.tasks ?? []).filter(task => matchesQuery(task.title));
  const filteredDelays = (operationalArchive.data?.delays ?? []).filter(delay => matchesQuery(delay.title));

  return <DashboardLayout><section className="mx-auto max-w-6xl">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold tracking-[0.14em] text-[#b18448]">استرجاع إداري مضبوط</p><h1 className="mt-2 text-3xl font-bold text-[#12352f]">الأرشيف المؤسسي</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-[#65766d]">سجل دائم للقرارات والمساءلات، وأرشيف تشغيلي مؤقت للمهام والمتعثرات دون حذف البيانات.</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e9f0ea] text-[#1f5a47]"><ArchiveRestore className="h-6 w-6" /></div></div>
    <div className="mt-7 rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5 shadow-[0_10px_30px_rgba(30,51,42,0.05)]"><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold text-[#5c6d64]">بحث في الأرشيف<input value={query} onChange={event => setQuery(event.target.value)} placeholder="مهمة، قرار، اسم، ملاحظة…" className="mt-1 h-10 w-full rounded-md border border-[#d8d1c5] bg-white px-3 text-sm font-normal" /></label><label className="text-xs font-bold text-[#5c6d64]">نوع السجل<select value={entityType} onChange={event => setEntityType(event.target.value as ArchiveEntityType)} className="mt-1 h-10 w-full rounded-md border border-[#d8d1c5] bg-white px-3 text-sm font-normal"><option value="">كل الأنواع</option>{Object.entries(entityLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="text-xs font-bold text-[#5c6d64]">حالة القرار<select value={status} onChange={event => setStatus(event.target.value as ArchiveStatus)} className="mt-1 h-10 w-full rounded-md border border-[#d8d1c5] bg-white px-3 text-sm font-normal"><option value="">كل الحالات المنتهية</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div></div>
    <div className="mt-5 rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5 shadow-[0_10px_30px_rgba(30,51,42,0.05)]"><div className="flex items-center gap-2"><FileCheck2 className="h-5 w-5 text-[#b18448]" /><h2 className="font-bold text-[#12352f]">السجلات المسترجعة</h2></div>{archive.isLoading ? <div className="mt-5 flex items-center gap-2 text-sm text-[#6e7e75]"><CircleDashed className="h-4 w-4 animate-spin" /> جارٍ استرجاع الأرشيف…</div> : filteredArchive.length ? <div className="mt-4 divide-y divide-[#eee8de]">{filteredArchive.map(row => <article key={row.approval.id} className="py-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-[#29463b]">{entityLabels[row.approval.entityType] || row.approval.entityType} رقم {row.approval.entityId}</p><p className="mt-1 text-xs text-[#75837c]">المرحلة: {row.approval.currentRole} · مقدم الطلب: {row.requesterName || "النظام"}</p></div><span className="rounded-full bg-[#edf3eb] px-3 py-1 text-xs font-bold text-[#386048]">{statusLabels[row.approval.status] || row.approval.status}</span></div>{row.approval.requestNote && <p className="mt-3 rounded-xl bg-[#fbfaf6] p-3 text-sm leading-6 text-[#52665c]"><strong>مذكرة الرفع: </strong>{row.approval.requestNote}</p>}{row.approval.decisionNote && <p className="mt-2 rounded-xl bg-[#edf4ed] p-3 text-sm leading-6 text-[#365447]"><strong>تعليق القرار: </strong>{row.approval.decisionNote}</p>}{row.relatedNotes.length ? <div className="mt-3 rounded-xl border border-[#eee8de] p-3"><p className="text-xs font-bold text-[#8a6731]">ملاحظات مؤرشفة مرتبطة</p>{row.relatedNotes.map(note => <p key={note.id} className="mt-2 text-sm leading-6 text-[#52665c]"><span className="font-bold">{note.source}: </span>{note.note} <span className="text-xs text-[#8a887f]">· {note.actorName || "النظام"}</span></p>)}</div> : null}<p className="mt-3 text-xs text-[#7a887f]">تاريخ القرار: {row.approval.decidedAt ? new Date(row.approval.decidedAt).toLocaleString("ar-SA") : "لم يسجل بعد"} · بواسطة {row.deciderName || "غير محدد"}</p></article>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-[#d8d1c5] bg-[#fbfaf6] px-5 py-10 text-center text-sm leading-7 text-[#738179]">لا توجد قرارات أو مساءلات منتهية ضمن عوامل التصفية المختارة.</div>}{archive.error ? <div role="alert" className="mt-4 flex items-center gap-2 rounded-xl bg-[#fbe9e4] p-3 text-sm text-[#a04a35]"><ShieldAlert className="h-4 w-4" />{archive.error.message || "تعذر استرجاع الأرشيف."}</div> : null}</div>
    <div className="mt-5 rounded-[1.5rem] border border-[#d8e6dc] bg-[#f7fbf7] p-5 shadow-[0_10px_30px_rgba(30,51,42,0.04)]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-[#12352f]">الأرشيف التشغيلي المؤقت</h2><p className="mt-1 text-xs leading-6 text-[#6e7e75]">المهام والمتعثرات التي أُخفيت من لوحات التشغيل دون حذفها. الاسترجاع متاح للقيادة.</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#e8f1e8] px-3 py-1 text-xs font-bold text-[#386048]">{(operationalArchive.data?.tasks.length ?? 0) + (operationalArchive.data?.delays.length ?? 0)} سجل</span><Button type="button" size="sm" disabled={archiveOperational.isPending} onClick={() => { if (window.confirm("سيبدأ هذا دورة تشغيل جديدة ويخفي المهام والمتعثرات الحالية من اللوحات دون حذفها. هل تريد المتابعة؟")) archiveOperational.mutate(); }} className="bg-[#12352f] hover:bg-[#1b4b3e]">{archiveOperational.isPending ? "جارٍ بدء الدورة…" : "بدء دورة تشغيل جديدة"}</Button></div></div>{archiveOperational.error && <p role="alert" className="mt-3 rounded-xl bg-[#fbe9e4] p-3 text-sm text-[#a04a35]">تعذر بدء دورة التشغيل: {archiveOperational.error.message}</p>}{operationalArchive.isLoading ? <p className="mt-4 text-sm text-[#6e7e75]">جارٍ تحميل الأرشيف التشغيلي…</p> : <div className="mt-4 grid gap-3 md:grid-cols-2">{filteredTasks.map(task => <article key={`task-${task.id}`} className="rounded-xl border border-[#e7e0d4] bg-white p-4"><p className="font-bold text-sm text-[#29463b]">مهمة: {task.title}</p><p className="mt-1 text-xs text-[#75837c]">أرشفت في {task.archivedAt ? new Date(task.archivedAt).toLocaleString("ar-SA") : "—"}</p><Button type="button" size="sm" variant="outline" className="mt-3" disabled={restore.isPending} onClick={() => restore.mutate({ entityType: "task", entityId: task.id })}>استرجاع المهمة</Button></article>)}{filteredDelays.map(delay => <article key={`delay-${delay.id}`} className="rounded-xl border border-[#e7e0d4] bg-white p-4"><p className="font-bold text-sm text-[#29463b]">متعثر: {delay.title}</p><p className="mt-1 text-xs text-[#75837c]">آخر تحديث {new Date(delay.updatedAt).toLocaleString("ar-SA")}</p><Button type="button" size="sm" variant="outline" className="mt-3" disabled={restore.isPending} onClick={() => restore.mutate({ entityType: "delay", entityId: delay.id })}>استرجاع المتعثر</Button></article>)}{!filteredTasks.length && !filteredDelays.length && <p className="md:col-span-2 rounded-xl border border-dashed border-[#d8d1c5] p-5 text-center text-sm text-[#738179]">لا توجد سجلات مؤرشفة مؤقتاً.</p>}</div>}{operationalArchive.error && <p role="alert" className="mt-3 rounded-xl bg-[#fbe9e4] p-3 text-sm text-[#a04a35]">{operationalArchive.error.message}</p>}</div>
    <div className="mt-5 rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5"><h2 className="font-bold text-[#12352f]">إيقاف أو تفعيل قسم</h2><p className="mt-1 text-xs leading-6 text-[#6e7e75]">إيقاف القسم يرشّح محتواه للأرشيف ولا يحذف شيئاً. التفعيل يعيده للعمل.</p>{units.isLoading ? <p className="mt-4 text-sm">جارٍ تحميل الأقسام…</p> : (units.data ?? []).filter((unit: { id: number; name: string; isActive?: boolean }) => matchesQuery(unit.name)).map((unit: { id: number; name: string; isActive?: boolean }) => <article key={unit.id} className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t pt-3"><div><p className="font-bold">{unit.name}</p><p className="text-xs text-[#718078]">{unit.isActive === false ? "مؤرشف" : "نشط"}</p></div><Button type="button" size="sm" variant="outline" disabled={setUnitActive.isPending} onClick={() => setUnitActive.mutate({ unitId: unit.id, isActive: unit.isActive === false })}>{unit.isActive === false ? "تفعيل القسم" : "إيقاف القسم للأرشيف"}</Button></article>)}</div>
  </section></DashboardLayout>;
}
