import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { Building2, ClipboardCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ManagerAssignmentRequestPage() {
  const people = trpc.court.people.list.useQuery({ personType: "administrative" });
  const units = trpc.court.units.list.useQuery();
  const request = trpc.court.approvals.createManagerAssignment.useMutation({ onSuccess: () => { toast.success("تم رفع طلب تسكين مدير القسم للتسلسل الإداري."); setForm({ profileId: "", unitId: "", reason: "" }); } });
  const [form, setForm] = useState({ profileId: "", unitId: "", reason: "" });
  return <DashboardLayout><section className="mx-auto max-w-4xl" dir="rtl"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.14em] text-[#b18448]">تسكين إداري بموافقة</p><h1 className="mt-2 text-3xl font-bold text-[#12352f]">طلب تعيين مدير قسم</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#65766d]">ينشأ الطلب من الموارد البشرية أو أمين المحكمة أو رئيس المحكمة، ثم يمر بالمراحل المطلوبة. لا تتغير صلاحية الموظف إلا بعد الموافقة النهائية.</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e9f0ea] text-[#1f5a47]"><ClipboardCheck className="h-6 w-6" /></div></header><form onSubmit={event => { event.preventDefault(); request.mutate({ profileId: Number(form.profileId), unitId: Number(form.unitId), reason: form.reason }); }} className="mt-7 rounded-[1.5rem] border border-[#e7e0d4] bg-white p-5 shadow-[0_10px_30px_rgba(30,51,42,0.05)]"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-[#65766d]">الموظف المرشح<select required value={form.profileId} onChange={event => setForm({ ...form, profileId: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm font-normal"><option value="">اختر الموظف</option>{people.data?.map(person => <option key={person.id} value={person.id}>{person.fullName} · {person.email ?? "دون بريد"}</option>)}</select></label><label className="text-xs font-bold text-[#65766d]">القسم<select required value={form.unitId} onChange={event => setForm({ ...form, unitId: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm font-normal"><option value="">اختر القسم</option>{units.data?.map(unit => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label></div><label className="mt-4 block text-xs font-bold text-[#65766d]">سبب التعيين أو التغيير<textarea required minLength={5} maxLength={2000} value={form.reason} onChange={event => setForm({ ...form, reason: event.target.value })} className="mt-1 min-h-28 w-full rounded-md border border-input bg-transparent p-3 text-sm font-normal" placeholder="اكتب سبب التسكين، مثل قرار تكليف أو شغور القسم." /></label><div className="mt-4 flex items-center gap-2 rounded-xl bg-[#f7fbf7] p-3 text-xs leading-6 text-[#557064]"><Building2 className="h-4 w-4 shrink-0 text-[#b18448]" />سيظهر الطلب في قائمة الاعتمادات للمرحلة المختصة، وسيُسجل كل انتقال في سجل الحركة.</div><Button disabled={request.isPending || people.isLoading || units.isLoading} className="mt-5 bg-[#006c35] hover:bg-[#00552b]">{request.isPending ? "جارٍ رفع الطلب…" : "رفع طلب التسكين"}</Button>{request.error && <p role="alert" className="mt-3 text-xs text-[#a04a35]">{request.error.message}</p>}</form></section></DashboardLayout>;
}
